version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
  frontend:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - backend


